# Generated by Django 4.2.1 on 2023-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
