# Generated by Django 4.2.1 on 2023-05-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0002_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='message1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='nom',
            new_name='nom1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sujet',
            new_name='sujet1',
        ),
        migrations.RenameField(
            model_name='rdv',
            old_name='email',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='rdv',
            old_name='message',
            new_name='message2',
        ),
        migrations.RenameField(
            model_name='rdv',
            old_name='nom',
            new_name='nom2',
        ),
    ]
