# Generated by Django 4.2.1 on 2023-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0003_rename_email_contact_email1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifrdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom3', models.CharField(max_length=255)),
                ('email3', models.EmailField(max_length=300)),
                ('tel1', models.CharField(max_length=300)),
                ('date1', models.DateField(max_length=1000)),
                ('message3', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Supprdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom4', models.CharField(max_length=255)),
            ],
        ),
    ]
