# Generated by Django 4.2.1 on 2023-06-18 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinetMedical', '0004_modifrdv_supprdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='userx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
