# Generated by Django 4.2.1 on 2023-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetMedical', '0005_rdv_userx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='userx',
        ),
    ]
