# Generated by Django 4.2.1 on 2023-06-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinetMedical', '0006_remove_rdv_userx'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
